### ISSUE TITLE
Flash failed to run flash

### ISSUE THREAD

**Issue by steve-shan** [lucapinello/CRISPResso#11]
Hello,

I was trying to use CRISPRessoPoll on my sequence file but received some FLASH error. The following is the log:

`[Command used]:
CRISPRessoPooled /Library/Frameworks/Python.framework/Versions/2.7/bin/CRISPRessoPooled -r1 FGC1478_s_1_1_AGGCAGAA-ACTGCATA.fastq.gz -r2 FGC1478_s_1_2_AGGCAGAA-ACTGCATA.fastq.gz -f CRISPResso1111.xlsx

[Execution log]:
Merging paired sequences with Flash...
[FLASH] Starting FLASH v1.2.11
[FLASH] Fast Length Adjustment of SHort reads
[FLASH]  
[FLASH] Input files:
[FLASH]     FGC1478_s_1_1_AGGCAGAA-ACTGCATA.fastq.gz
[FLASH]     FGC1478_s_1_2_AGGCAGAA-ACTGCATA.fastq.gz
[FLASH]  
[FLASH] Output files:
[FLASH]     CRISPRessoPooled_on_FGC1478_s_1_1_AGGCAGAA-ACTGCATA_FGC1478_s_1_2_AGGCAGAA-ACTGCATA/out.extendedFrags.fastq.gz
[FLASH]     CRISPRessoPooled_on_FGC1478_s_1_1_AGGCAGAA-ACTGCATA_FGC1478_s_1_2_AGGCAGAA-ACTGCATA/out.notCombined_1.fastq.gz
[FLASH]     CRISPRessoPooled_on_FGC1478_s_1_1_AGGCAGAA-ACTGCATA_FGC1478_s_1_2_AGGCAGAA-ACTGCATA/out.notCombined_2.fastq.gz
[FLASH]     CRISPRessoPooled_on_FGC1478_s_1_1_AGGCAGAA-ACTGCATA_FGC1478_s_1_2_AGGCAGAA-ACTGCATA/out.hist
[FLASH]     CRISPRessoPooled_on_FGC1478_s_1_1_AGGCAGAA-ACTGCATA_FGC1478_s_1_2_AGGCAGAA-ACTGCATA/out.histogram
[FLASH]  
[FLASH] Parameters:
[FLASH]     Min overlap:           4
[FLASH]     Max overlap:           100
[FLASH]     Max mismatch density:  0.250000
[FLASH]     Allow "outie" pairs:   false
[FLASH]     Cap mismatch quals:    false
[FLASH]     Combiner threads:      8
[FLASH]     Input format:          FASTQ, phred_offset=33
[FLASH]     Output format:         FASTQ, phred_offset=33, gzip
[FLASH]  
[FLASH] Starting reader and writer threads
[FLASH] Starting 8 combiner threads
[FLASH] Processed 25000 read pairs
[FLASH] Processed 50000 read pairs
[FLASH] Processed 75000 read pairs
[FLASH] Processed 100000 read pairs
[FLASH] Processed 125000 read pairs
[FLASH] Processed 150000 read pairs
[FLASH] Processed 175000 read pairs
[FLASH] Processed 200000 read pairs
[FLASH] Processed 225000 read pairs
[FLASH] Processed 250000 read pairs
[FLASH] Processed 275000 read pairs
[FLASH] Processed 300000 read pairs
[FLASH] Processed 325000 read pairs
[FLASH] Processed 350000 read pairs
[FLASH] Processed 375000 read pairs
[FLASH] ERROR: Qual string length (55) not the same as sequence length (250) (file "FGC1478_s_1_1_AGGCAGAA-ACTGCATA.fastq.gz", near line 1502597)
[FLASH] FLASH did not complete successfully; exiting with failure status (1)

ERROR: Flash failed to run, please check the log file.
`

It seems like there's something wrong with my fastq file because I can run your test example without any problem, although that did not require CRISPRessoPoll.

**Comment by lucapinello** [comment]
Hi Steve,
Yes the problem is that your fastq file is either truncated or malformed (the quality string for one read is shorter than the read itself).
