### ISSUE TITLE
Specify the FLASH --max-overlap parameter?

### ISSUE THREAD

**Issue by martinaryee** [lucapinello/CRISPResso#16]
I get the following warning from FLASH about a high proportion of paired end reads overlapping by more than 100bp. This pooled dataset has many short amplicons and 150bp PE reads, so this is probably to be expected. Is it possible to specify the ` --max-overlap (-M)` parameter to fix this?

```
[FLASH]  
[FLASH] Read combination statistics:
[FLASH]     Total pairs:      2554170
[FLASH]     Combined pairs:   415920
[FLASH]     Uncombined pairs: 2138250
[FLASH]     Percent combined: 16.28%
[FLASH]  
[FLASH] Writing histogram files.
[FLASH] WARNING: An unexpectedly high proportion of combined pairs (10.04%)
overlapped by more than 100 bp, the --max-overlap (-M) parameter.  Consider
increasing this parameter.  (As-is, FLASH is penalizing overlaps longer than
100 bp when considering them for possible combining!)
```

**Comment by lucapinello** [comment]
Yes you can with --max_paired_end_reads_overlap. Please let me know if this fixes your problem.

**Comment by martinaryee** [comment]
Yes - The `--max_paired_end_reads_overlap` removes the FLASH warning and fixes the problem. Thanks!

**Comment by lucapinello** [comment]
Great!

**Comment by asgiraldoc** [comment]
Hey guys, I had the same problem and your solution didn't work for me :(
