### ISSUE TITLE
Running CRISPResso - query

### ISSUE THREAD

**Issue by frankbioinfo** [lucapinello/CRISPResso#22]
hello Developer, 

Thank you for developing  this tool. 

I am not sure which module should I use for my purpose, we have crispr guided to a target region. we then sequenced the genomic dna (pcr product) that targets this region using miseq 2x250 + 10bp Index1 + 8bp Index2
I used two two different approach
1. using fastq and 
2. using the bam file (alignment using bwa)

I have attached plots from both the steps,  having difficulty in understanding the plots. could you please help in this?

[4b.usingbam.pdf](https://github.com/lucapinello/CRISPResso/files/1195409/4b.usingbam.pdf)
[4b.usingfastq.pdf](https://github.com/lucapinello/CRISPResso/files/1195410/4b.usingfastq.pdf)

**Comment by lucapinello** [comment]
We don't support reads aligned through BWA so I am not sure what I am looking at. You should use CRISPResso with paired end reads in fastq format. I suggest you to read carefully the paper (http://rdcu.be/jgvL) and supplementary material: https://www.readcube.com/articles/supplement?doi=10.1038%2Fnbt.3583&index=0&ssl=1&st=f5e8a734a3bfafe4c31a97f8993f72d1&preview=1 where we explain in detail the required inputs, parameters and the different tools.

The plot 4b.usingbam.pdf looks more reasonable to me.

Regards,

Luca
