### ISSUE TITLE
no of reads from pie chart and alleles do not add up 

### ISSUE THREAD

**Issue by frankbioinfo** [lucapinello/CRISPResso#23]
Hi I am using crispr guided to a target region. we then sequenced the genomic dna (pcr product) that targets this region using miseq 2x250 + 10bp Index1 + 8bp Index2 (as defined in my previous question
[Alleles_frequency.txt](https://github.com/lucapinello/CRISPResso/files/1232660/Alleles_frequency.txt)
[alleles.pdf](https://github.com/lucapinello/CRISPResso/files/1232661/alleles.pdf)
[Quantification_of_editing_frequency.txt](https://github.com/lucapinello/CRISPResso/files/1232662/Quantification_of_editing_frequency.txt)
[pie.pdf](https://github.com/lucapinello/CRISPResso/files/1232663/pie.pdf)

)

On reading the paper and supplementary we decided to use CRISPResso.py for our analysis, ~CRISPResso.py --trim_sequences -r1 sample _R1_001.fastq.gz  -r2  sample_R2_001.fastq.gz -a CCTCGCAGACATTAAAGCCCgtgctttgcaggcccgaggggcgagaggttaccactgcaatcgagagacggccaccactgccatcggaggggggggtggcccgggtggaggtggcactcgggccatcgatgagggaggtggcagagacagcagcaGTGGTGATGGTAGTGAGGCC -g grna seq -o sample_out

My question is after successful run, the number of reads show in the pie chart and the alleles frequency do not add up (so the plot shows only site above 0.2%, but even when you look at the text file the number of reads is confusing). Was wondering if something is wrong our command or are we comprehending it in a wrong way. Have attached all the figures and text associated with it.

Thank you.

**Comment by lucapinello** [comment]
Hi Frank,

Let me explain the logic we are using.

By default CRISPResso is using a window around the cut site of 1bp on each side to classify reads as "modified". If the indel are outside this window the alleles will be reported in the file as Unmodified True. If you sum  '#Reads' for the  rows with Unmodified True you will get 2807 reads that is the same number you have in the pie chart. You can do the same for Unmodified False to get the NHEJ reads. If you want to quantify indels also further away from the cleavage site as modified you can use the parameter -w, for example -w 10.

For the graphical report we report reads up to 0.2% to avoid to have a huge figure but you can change this with the options:

 --offset_around_cut_to_plot OFFSET_AROUND_CUT_TO_PLOT
                        Offset to use to summarize alleles around the cut site
                        in the alleles table plot. (default: 20)
  --min_frequency_alleles_around_cut_to_plot MIN_FREQUENCY_ALLELES_AROUND_CUT_TO_PLOT
                        Minimum % reads required to report an allele in the
                        alleles table plot. (default: 0.2)
  --max_rows_alleles_around_cut_to_plot MAX_ROWS_ALLELES_AROUND_CUT_TO_PLOT
                        Maximum number of rows to report in the alleles table
                        plot. (default: 50)

Hope this is helpful.

Luca

**Comment by frankbioinfo** [comment]
Thank you @lucapinello  it was helpful
