### ISSUE TITLE
Different results from online and command line CRISPResso with same data and parameters

### ISSUE THREAD

**Issue by miikaelf** [lucapinello/CRISPResso#27]
Hi Luca,

I'm running CRISPResso in single read mode normally from command line, and checked with the online version, and it seems they output considerably different results.  Specifically, I'm getting out about 50% less NHEJ from command line version compared to online version across samples, with the same data and parameters (see example and files attached below).  So currently I don´t know which to trust.
[H6_R2.fastq.tar.gz](https://github.com/lucapinello/CRISPResso/files/1293519/H6_R2.fastq.tar.gz)
[H6_R2.fastq.tar.gz](https://github.com/lucapinello/CRISPResso/files/1293520/H6_R2.fastq.tar.gz)

 

I'm wondering if this is because of the specific installation on my machine, or whether the backend of online and command-line veersions differ, or whether the default parameters between the two differ. Any thoughts?

On another matter, does a CRISPResso forum exist? Sometimes would be better to address the question broadly. Any case, thanks for the great software.

PARAMETERS:
Online:
-Single-end reads
-Seq homology for HDR: 98%
-Window size: 25
-Min average read qual: 20
-Min single bp qual: 20
-Exclude bp from left: 5
-Exclude bp from right: 40
-Amplicon seq: TCGTGCTGCTTCATGTGGTCGGGGTAGCGGCTGAAGCACTGCACGCCGTAGGTCAGGGTGGTCACGAGGGTGGGCCAGGGCACGGGCAGCTTGCCGGTGGTGCAGATGAACTTCAGGGTCAGCTTGCCGTAGGT 
-HDR seq: TCGTGCTGCTTCATGTGGTCGGGGTAGCGGCTGAAGCACTGCACGCCGTGGCTCAGGGTGGTCACGAGGGTGGGCCAGGGCACGGGCAGCTTGCCGGTGGTGCAGATGAACTTCAGGGTCAGCTTGCCGTAGGT  
-Guide seq: ACCTACGGCGTGCAGTGCTT 
-All else default

Command line:
CRISPResso -r1 H6_R2.fastq -g ACCTACGGCGTGCAGTGCTT -a TCGTGCTGCTTCATGTGGTCGGGGTAGCGGCTGAAGCACTGCACGCCGTAGGTCAGGGTGGTCACGAGGGTGGGCCAGGGCACGGGCAGCTTGCCGGTGGTGCAGATGAACTTCAGGGTCAGCTTGCCGTAGGT -e TCGTGCTGCTTCATGTGGTCGGGGTAGCGGCTGAAGCACTGCACGCCGTGGCTCAGGGTGGTCACGAGGGTGGGCCAGGGCACGGGCAGCTTGCCGGTGGTGCAGATGAACTTCAGGGTCAGCTTGCCGTAGGT -o test --exclude_bp_from_left 5 --exclude_bp_from_right 40 --save_also_png -w 25 -q 20 -s 20

**Comment by lucapinello** [comment]
Hi, Happy to take a look. Can you send me the zip file you got from the website and output folder from the command line obtained in your machine? Also which version of CRISPResso do you have installed in your machine?

**Comment by miikaelf** [comment]
Many thanks! The CRISPREsso I'm running is v. 1.0.5. See outputs attached.
[CRISPResso_on_H6_R2.tar.gz](https://github.com/lucapinello/CRISPResso/files/1300647/CRISPResso_on_H6_R2.tar.gz)
[CRISPResso_Report_qS4eA8.zip](https://github.com/lucapinello/CRISPResso/files/1300707/CRISPResso_Report_qS4eA8.zip)

**Comment by lucapinello** [comment]
This potentially explain the problem. Can you please download the latest version 1.0.8 and try again?
We have changed defaults and improved the quantification for single end reads since then. 
Happy to take a look if you still have problem also with  the latest version.

Thanks, Luca

**Comment by miikaelf** [comment]
Hi Luca,
Thanks for the tip. I updated to 1.0.8 and re-ran it - but the result is the same. The output looks identical to 1.0.5 as far as I can tell (attached).
I do get two warnings now when I run (below). Any thoughts?

WARNING @ Thu, 14 Sep 2017 18:12:48:
Skipping:/home/michael/Desktop/Genomics/deindexer/files/Chris/Liver/testing/CRISPResso_on_H6_R2/H6_R2_filtered.fastq.gz
and 
/usr/lib/pymodules/python2.7/matplotlib/collections.py:548: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == 'face':




[CRISPResso_on_H6_R2_v1.0.8.tar.gz](https://github.com/lucapinello/CRISPResso/files/1304753/CRISPResso_on_H6_R2_v1.0.8.tar.gz)

**Comment by lucapinello** [comment]
Hi Michael,

Looking at the log I think I now the source of confusion.

On the web when you select 25, it creates a windows of 50 essentially it is 25 on each side.

In the command line instead to get the same window you need to specify the option  -w 50 and not -w 25 as you have currently.

Try to run the command again with the option -w 50 and please let me know if this fixes the problem.
