### ISSUE TITLE
crispressoweb dockerfile

### ISSUE THREAD

**Issue by chriscatalyticds** [lucapinello/CRISPResso#28]
Hi @lucapinello, 

Would you be willing to share the dockerfile for the [crispressoweb](https://hub.docker.com/r/lucapinello/crispressoweb/) docker image you have listed on docker hub?

**Comment by lucapinello** [comment]
Hi Chris,

We are working on a manuscript for CRISPResso2 and we will release the source code of the webapp and Docker Container as soon as we have it on the bioarvix. **The container is still unstable and not fully tested. So I will advise not to use it for now.**

Chris what was your plan with this webapp? Are you willing to share with me your usage case? 

Regards,

Luca
