### ISSUE TITLE
ERROR: If using all scalar values, you must pass an index 

### ISSUE THREAD

**Issue by strohmjeff** [lucapinello/CRISPResso#29]
Hi there,

I am attempting your pipeline with single end reads (since my overlap is over 65bp and I get an error from flash when trying to merge. Is there any way to adjust flash params?). Reads were quality filtered and merged with usearch. 

I have attached my merged reads and my reference sequence. They gave reasonable results with GATK/MuTect2...

I get this error, thanks for your help!:

~~~CRISPResso~~~
-Analysis of CRISPR/Cas9 outcomes from deep sequencing data-

                      )
                     (
                    __)__
                 C\|     |
                   \     /
                    \___/
             

[Luca Pinello 2015, send bugs, suggestions or *green coffee* to lucapinello AT gmail DOT com]

Version 1.0.8

INFO  @ Tue, 24 Oct 2017 10:05:27:
	 Creating Folder CRISPResso_on_JC04-4-CT13_S4_filter 

INFO  @ Tue, 24 Oct 2017 10:05:27:
	 Done! 

INFO  @ Tue, 24 Oct 2017 10:05:27:
	 Preparing files for the alignment... 

INFO  @ Tue, 24 Oct 2017 10:05:27:
	 Done! 

INFO  @ Tue, 24 Oct 2017 10:05:27:
	 Aligning sequences... 

INFO  @ Tue, 24 Oct 2017 10:09:34:
[JC04-4-CT13_S4_filter.fastq.gz](https://github.com/lucapinello/CRISPResso/files/1411814/JC04-4-CT13_S4_filter.fastq.gz)
[JC04-4-CT13_reference.txt](https://github.com/lucapinello/CRISPResso/files/1411820/JC04-4-CT13_reference.txt)



	 Align sequences to reverse complement of the amplicon... 

INFO  @ Tue, 24 Oct 2017 10:09:34:
	 Done! 

INFO  @ Tue, 24 Oct 2017 10:13:35:
	 Quantifying indels/substitutions... 

CRITICAL @ Tue, 24 Oct 2017 10:13:35:
	 Unexpected error, please check your input.

ERROR: If using all scalar values, you must pass an index

**Comment by lucapinello** [comment]
Hi
1) Regarding flash, yes you can run it before running CRISPResso with the options you like and then run CRISPResso on the merged file specifying a single file.

2)  Looking at your reference and at few reads of your fastq file it seems the reference is too long.

The refererence is:
TCTGCTTACTGCAACTCGCTCCGGCCGCTGGGCGTAGCTGCGACTCGGCGGAGTCCCGGCGGCGCGTCCTTGTTCTAACCCGGCGCGCCATGACCGTCGCGCGGCCGAGCGTGCCCGCGGCGCTGCCCCTCCTCGGGGAGCTGCCCCGGCTGCTGCTGCTGGTGCTGTTGTGCCTGCCGGCCGTGTGGGGTGAGTAGGGGCCCGGCGGCCGGGGAAGCCCCTGGGCTGGGTGGGAGGTCCAAGTCGGTCTCTGAGACACGCACAGGGGCCGGCGACTTGGCAGGTGGGGAGCTTGGCCCGCGGTCGTGGTTCCCGCCGTCCTGTGCCTTTAAGGCTCTCGCCGCTCACCAGCATTTGGGGCTCCTGCTGTGTCGGCCCCCAGCTGACTTGGCTTTAGGGGTCGGCGTGGAGGGTTAAAGAGGCCCCGGCTGGGTTTGCGGAGCAGCCAAGCCTGGCAAAATCGAAAGGGAGGGCTCAAAGAGACTGTATCCTTAACCCCCAAAAAGCTGGTCTAAAAGGATGGGAGGCCAGACCGCTGACCGTTCCCCACTCTCGACAGAGTCCAGCCGTGTGGAGCACACGATGCTGCAAACTTGCATGTCATCTCTTTCAGGTGTGGCATTTCAAGGGGGCTTGTGTCTTGAAAACAGCAACTGTGAGGACACTTGATAGTCATTTCCTTCAGTTCTGCTTTTGTCTCCCTAGGTGACTGTGGCCTTCCCCCAGATGTACCTAATGCCCAGCCAGCTTTGGAAGGCCGTACAAGTTTTCCCGAGGATACTGTAATAACGTACAAATGTGAAGAAAGCTTTGTGAAAATTCCTGGCGAGAAGGACTCAGTGATCTGCCTTAAGGGCAGTCAATGGTCAGATATTGAAGAGTTCTGCAATCGTAAGTTCTTCATCTTTTTAGAAAAGTTCTGGGAATGGAATGTATCTTAAATTTATTTTTATATACCTTTGGAGTGACTAGTAATTGATAGTTCTCTAGCGTTACTAAACCCCAGGGTATACCCTGTTGGCACGTCACACTC

One of the read is:

CAGATCACTGAGTCCTTCTCGCCAGGAATTTTCACAAAGCTTTCTTCACATTTGTACGTTATTACAGTATACAGTATAATAACTTGTACGGCCTCGGGAAAACTTGTACGGCCTTCCAAAGCTGGCTGGGCATTAGGTACATCTGGGGGAAGGCCACAGTCACCTAGGGAGACAAAAGCAGAACTGAAGGAAATGACTATCAAGTGTCCTCACAGTTGCTGTTTTCAAGACACAAGCCCCCTTGAAATGCCACACCTG

So something is wrong here, please double check the provided reference.

**Comment by strohmjeff** [comment]
OK thanks, yes I didn't realize the reference had to only cover the active region. I was using the entire gene.  Shortening it to the active region observed in GATK worked. 

Thanks again

-Jeff

**Comment by lucapinello** [comment]
Hi Jeff, cool. 

Closing this.
