### ISSUE TITLE
mutation frequency plot 

### ISSUE THREAD

**Issue by frankbioinfo** [lucapinello/CRISPResso#30]
hello @lucapinello 

Thank you for your help so far, i was able to get CRISPResso working, I had a question with respeect to the mutation frequency plot, as seen below 
<img width="502" alt="screen shot 2017-11-01 at 3 19 36 pm" src="https://user-images.githubusercontent.com/27443838/32295941-b71aef8c-bf18-11e7-94a4-9a4a62059ed5.png">

What could be reason we seen peaks at the beginning and end of the sequence, I can see this in almost all my sequences i did used '--trim_sequence' for trimming adapters. 

Thank you once again

**Comment by lucapinello** [comment]
Hey Frank,

This is very common for samples where you have trimming artifacts. The trimming operation may not be perfect with your sample. Since you are using the window strategy and those events are far away from the cleavage site you can safely ignore them (since they will not be quantified).
