### ISSUE TITLE
Unexpected error: invalid literal for int() with base 10: '0rc1'

### ISSUE THREAD

**Issue by strohmjeff** [lucapinello/CRISPResso#33]
[JC04-4-CT13_short.txt](https://github.com/lucapinello/CRISPResso/files/1473019/JC04-4-CT13_short.txt)

[JC04-4-CT13_S4_filter.fastq.gz](https://github.com/lucapinello/CRISPResso/files/1473021/JC04-4-CT13_S4_filter.fastq.gz)

Hi there,

I ran the web version and these files generated meaningful output, but when running the following with the command line version, I get the following error:

earnest@biolinux8[CRISPResso-master] python CRISPResso.py -r1 /home/earnest/Jeff.S/CRISPR_test/merged/filter/JC04-4-CT13_S4_filter.fastq -a TGCATGTCATCTCTTTCAGGTGTGGCATTTCAAGGGGGCTTGTGTCTTGAAAACAGCAACTGTGAGGACACTTGATAGTCATTTCCTTCAGTTCTGCTTTTGTCTCCCTAGGTGACTGTGGCCTTCCCCCAGATGTACCTAATGCCCAGCCAGCTTTGGAAGGCCGTACAAGTTTTCCCGAGGATACTGTAATAACGTACAAATGTGAAGAAAGCTTTGTGAAAATTCCTGGCGAGAAGGACTCAGT
  
~~~CRISPResso~~~
-Analysis of CRISPR/Cas9 outcomes from deep sequencing data-

                      )
                     (
                    __)__
                 C\|     |
                   \     /
                    \___/
             

[Luca Pinello 2015, send bugs, suggestions or *green coffee* to lucapinello AT gmail DOT com]

Version 1.0.8

WARNING @ Tue, 14 Nov 2017 16:39:12:
	 Folder CRISPResso_on_JC04-4-CT13_S4_filter already exists. 

INFO  @ Tue, 14 Nov 2017 16:39:12:
	 Preparing files for the alignment... 

INFO  @ Tue, 14 Nov 2017 16:39:12:
	 Done! 

INFO  @ Tue, 14 Nov 2017 16:39:12:
	 Aligning sequences... 

INFO  @ Tue, 14 Nov 2017 16:40:01:
	 Align sequences to reverse complement of the amplicon... 

INFO  @ Tue, 14 Nov 2017 16:40:01:
	 Done! 

INFO  @ Tue, 14 Nov 2017 16:40:23:
	 Quantifying indels/substitutions... 

INFO  @ Tue, 14 Nov 2017 16:43:49:
	 Done! 

INFO  @ Tue, 14 Nov 2017 16:43:49:
	 Calculating indel distribution based on the length of the reads... 

INFO  @ Tue, 14 Nov 2017 16:43:51:
	 Done! 

INFO  @ Tue, 14 Nov 2017 16:43:51:
	 Calculating alleles frequencies... 

CRITICAL @ Tue, 14 Nov 2017 16:43:51:
	 Unexpected error, please check your input.

ERROR: invalid literal for int() with base 10: '0rc1'

**Comment by lucapinello** [comment]
This may be related to your local version of Python and the libraries you have installed. 
Some things to check:
1) Operating System ?
2) Are you using Anaconda Python 2.7?
3) Do you have the same problem using the docker version?

**Comment by strohmjeff** [comment]
Thanks, it's Ubuntu v14, I suspected that may be the case, and set it to
upgrade to 16 overnight.

I'm calling python 3 by default. I'll follow up with these and let you know
if I can't resolve it.

On Nov 14, 2017 8:13 PM, "Luca Pinello" <notifications@github.com> wrote:

This may be related to your local version of Python and the libraries you
have installed.
Some things to check:

   1. Operating System ?
   2. Are you using Anaconda Python 2.7?
   3. Do you have the same problem using the docker version?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/lucapinello/CRISPResso/issues/33#issuecomment-344480810>,
or mute the thread

**Comment by lucapinello** [comment]
Try to install Anaconda Python 2.7 and please let me know if this fixes your problem. 
Python 3 is not currently supported.

**Comment by strohmjeff** [comment]
Hi Luca,

I've installed and activated my anaconda 2.7 environment.

python --version yields "Python 2.7.14 :: Anaconda custom (64-bit)"

when I run CRISPResso.py from within the -master directory with the
following command:

python CRISPResso.py -r1
/home/earnest/Jeff.S/CRISPR_test/merged/filter/JC04-4-CT13_S4_filter.fastq
-a
TGCATGTCATCTCTTTCAGGTGTGGCATTTCAAGGGGGCTTGTGTCTTGAAAACAGCAACTGTGAGGACACTTGATAGTCATTTCCTTCAGTTCTGCTTTTGTCTCCCTAGGTGACTGTGGCCTTCCCCCAGATGTACCTAATGCCCAGCCAGCTTTGGAAGGCCGTACAAGTTTTCCCGAGGATACTGTAATAACGTACAAATGTGAAGAAAGCTTTGTGAAAATTCCTGGCGAGAAGGACTCAGT

I now get:

CRITICAL @ Wed, 15 Nov 2017 12:23:29:
     You need to install pandas module to use CRISPResso!

However, 'conda list' shows  pandas                    0.20.3
py27h820b67f_2  installed.

pip install CRISPResso comes back as already satisfied.

However, when I try CRISPResso --help, I get "not defined"

How should I be calling python and CRISPResso?

Thanks for you help!

-Jeff

**Comment by lucapinello** [comment]
You should not run CRISPResso from the master directory. From within that directory try to run:

python setup.py install

This should reinstall CRISPResso for Anaconda and will create the script.

If this doesn't work you may want to consider to use the docker image.

**Comment by strohmjeff** [comment]
OK I tried that a few days ago, but here it is again, if you don't see
anything out of place I will try the docker thanks

(py27) earnest@biolinux8[CRISPResso-master] python setup.py install
[12:46PM]
running install
running bdist_egg
running egg_info
writing requirements to CRISPResso.egg-info/requires.txt
writing CRISPResso.egg-info/PKG-INFO
writing top-level names to CRISPResso.egg-info/top_level.txt
writing dependency_links to CRISPResso.egg-info/dependency_links.txt
writing entry points to CRISPResso.egg-info/entry_points.txt
reading manifest file 'CRISPResso.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'CRISPResso.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/CRISPResso
creating build/bdist.linux-x86_64/egg/CRISPResso/data
copying build/lib/CRISPResso/data/NexteraPE-PE.fa ->
build/bdist.linux-x86_64/egg/CRISPResso/data
copying build/lib/CRISPResso/data/.DS_Store ->
build/bdist.linux-x86_64/egg/CRISPResso/data
copying build/lib/CRISPResso/data/TruSeq3-PE-2.fa ->
build/bdist.linux-x86_64/egg/CRISPResso/data
copying build/lib/CRISPResso/data/TRIMMOMATIC_LICENSE ->
build/bdist.linux-x86_64/egg/CRISPResso/data
copying build/lib/CRISPResso/data/TruSeq2-PE.fa ->
build/bdist.linux-x86_64/egg/CRISPResso/data
copying build/lib/CRISPResso/data/TruSeq3-PE.fa ->
build/bdist.linux-x86_64/egg/CRISPResso/data
copying build/lib/CRISPResso/data/TruSeq3-SE.fa ->
build/bdist.linux-x86_64/egg/CRISPResso/data
copying build/lib/CRISPResso/data/trimmomatic-0.33.jar ->
build/bdist.linux-x86_64/egg/CRISPResso/data
copying build/lib/CRISPResso/data/TruSeq2-SE.fa ->
build/bdist.linux-x86_64/egg/CRISPResso/data
copying build/lib/CRISPResso/CRISPRessoCountCORE.py ->
build/bdist.linux-x86_64/egg/CRISPResso
copying build/lib/CRISPResso/.DS_Store ->
build/bdist.linux-x86_64/egg/CRISPResso
copying build/lib/CRISPResso/CRISPRessoCORE.py ->
build/bdist.linux-x86_64/egg/CRISPResso
copying build/lib/CRISPResso/__init__.pyc ->
build/bdist.linux-x86_64/egg/CRISPResso
copying build/lib/CRISPResso/CRISPRessoWGSCORE.py ->
build/bdist.linux-x86_64/egg/CRISPResso
copying build/lib/CRISPResso/CRISPRessoPooledCORE.py ->
build/bdist.linux-x86_64/egg/CRISPResso
copying build/lib/CRISPResso/CRISPRessoCORE.pyc ->
build/bdist.linux-x86_64/egg/CRISPResso
copying build/lib/CRISPResso/__init__.py ->
build/bdist.linux-x86_64/egg/CRISPResso
copying build/lib/CRISPResso/CRISPRessoPooledWGSCompareCORE.py ->
build/bdist.linux-x86_64/egg/CRISPResso
copying build/lib/CRISPResso/__main__.py ->
build/bdist.linux-x86_64/egg/CRISPResso
copying build/lib/CRISPResso/CRISPRessoCompareCORE.py ->
build/bdist.linux-x86_64/egg/CRISPResso
byte-compiling
build/bdist.linux-x86_64/egg/CRISPResso/CRISPRessoCountCORE.py to
CRISPRessoCountCORE.pyc
byte-compiling build/bdist.linux-x86_64/egg/CRISPResso/CRISPRessoWGSCORE.py
to CRISPRessoWGSCORE.pyc
byte-compiling
build/bdist.linux-x86_64/egg/CRISPResso/CRISPRessoPooledCORE.py to
CRISPRessoPooledCORE.pyc
byte-compiling
build/bdist.linux-x86_64/egg/CRISPResso/CRISPRessoPooledWGSCompareCORE.py
to CRISPRessoPooledWGSCompareCORE.pyc
byte-compiling build/bdist.linux-x86_64/egg/CRISPResso/__main__.py to
__main__.pyc
byte-compiling
build/bdist.linux-x86_64/egg/CRISPResso/CRISPRessoCompareCORE.py to
CRISPRessoCompareCORE.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying CRISPResso.egg-info/PKG-INFO ->
build/bdist.linux-x86_64/egg/EGG-INFO
copying CRISPResso.egg-info/SOURCES.txt ->
build/bdist.linux-x86_64/egg/EGG-INFO
copying CRISPResso.egg-info/dependency_links.txt ->
build/bdist.linux-x86_64/egg/EGG-INFO
copying CRISPResso.egg-info/entry_points.txt ->
build/bdist.linux-x86_64/egg/EGG-INFO
copying CRISPResso.egg-info/requires.txt ->
build/bdist.linux-x86_64/egg/EGG-INFO
copying CRISPResso.egg-info/top_level.txt ->
build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
CRISPResso.CRISPRessoCORE: module references __file__
CRISPResso.CRISPRessoCompareCORE: module references __file__
CRISPResso.CRISPRessoCountCORE: module references __file__
CRISPResso.CRISPRessoPooledCORE: module references __file__
CRISPResso.CRISPRessoPooledWGSCompareCORE: module references __file__
CRISPResso.CRISPRessoWGSCORE: module references __file__
creating 'dist/CRISPResso-1.0.8-py2.7.egg' and adding
'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing CRISPResso-1.0.8-py2.7.egg
removing
'/home/earnest/anaconda2/envs/py27/lib/python2.7/site-packages/CRISPResso-1.0.8-py2.7.egg'
(and everything under it)
creating
/home/earnest/anaconda2/envs/py27/lib/python2.7/site-packages/CRISPResso-1.0.8-py2.7.egg
Extracting CRISPResso-1.0.8-py2.7.egg to
/home/earnest/anaconda2/envs/py27/lib/python2.7/site-packages
CRISPResso 1.0.8 is already the active version in easy-install.pth
Installing CRISPRessoWGS script to /home/earnest/anaconda2/envs/py27/bin
Installing CRISPRessoPooledWGSCompare script to
/home/earnest/anaconda2/envs/py27/bin
Installing CRISPRessoCount script to /home/earnest/anaconda2/envs/py27/bin
Installing CRISPRessoCompare script to /home/earnest/anaconda2/envs/py27/bin
Installing CRISPRessoPooled script to /home/earnest/anaconda2/envs/py27/bin
Installing CRISPResso script to /home/earnest/anaconda2/envs/py27/bin

Installed
/home/earnest/anaconda2/envs/py27/lib/python2.7/site-packages/CRISPResso-1.0.8-py2.7.egg
Processing dependencies for CRISPResso==1.0.8
Searching for seaborn==0.8.1
Best match: seaborn 0.8.1
Adding seaborn 0.8.1 to easy-install.pth file

Using /home/earnest/.local/lib/python2.7/site-packages
Searching for argparse==1.4.0
Best match: argparse 1.4.0
Processing argparse-1.4.0-py2.7.egg
argparse 1.4.0 is already the active version in easy-install.pth

Using
/home/earnest/.local/lib/python2.7/site-packages/argparse-1.4.0-py2.7.egg
Searching for biopython==1.70
Best match: biopython 1.70
Adding biopython 1.70 to easy-install.pth file

Using /home/earnest/.local/lib/python2.7/site-packages
Searching for matplotlib==2.1.0
Best match: matplotlib 2.1.0
Adding matplotlib 2.1.0 to easy-install.pth file

Using /home/earnest/anaconda2/envs/py27/lib/python2.7/site-packages
Searching for pandas==0.21.0rc1
Best match: pandas 0.21.0rc1
Processing pandas-0.21.0rc1-py2.7-linux-x86_64.egg
pandas 0.21.0rc1 is already the active version in easy-install.pth

Using
/home/earnest/.local/lib/python2.7/site-packages/pandas-0.21.0rc1-py2.7-linux-x86_64.egg
Searching for numpy==1.13.3
Best match: numpy 1.13.3
Adding numpy 1.13.3 to easy-install.pth file

Using /home/earnest/anaconda2/envs/py27/lib/python2.7/site-packages
Searching for pyparsing==2.2.0
Best match: pyparsing 2.2.0
Adding pyparsing 2.2.0 to easy-install.pth file

Using /home/earnest/anaconda2/envs/py27/lib/python2.7/site-packages
Searching for cycler==0.10.0
Best match: cycler 0.10.0
Adding cycler 0.10.0 to easy-install.pth file

Using /home/earnest/anaconda2/envs/py27/lib/python2.7/site-packages
Searching for pytz==2017.2
Best match: pytz 2017.2
Adding pytz 2017.2 to easy-install.pth file

Using /home/earnest/anaconda2/envs/py27/lib/python2.7/site-packages
Searching for subprocess32==3.2.7
Best match: subprocess32 3.2.7
Adding subprocess32 3.2.7 to easy-install.pth file

Using /home/earnest/anaconda2/envs/py27/lib/python2.7/site-packages
Searching for backports.functools-lru-cache==1.4
Best match: backports.functools-lru-cache 1.4
Adding backports.functools-lru-cache 1.4 to easy-install.pth file

Using /home/earnest/anaconda2/envs/py27/lib/python2.7/site-packages
Searching for python-dateutil==2.6.1
Best match: python-dateutil 2.6.1
Adding python-dateutil 2.6.1 to easy-install.pth file

Using /home/earnest/anaconda2/envs/py27/lib/python2.7/site-packages
Searching for six==1.11.0
Best match: six 1.11.0
Adding six 1.11.0 to easy-install.pth file

Using /home/earnest/anaconda2/envs/py27/lib/python2.7/site-packages
Finished processing dependencies for CRISPResso==1.0.8

Python package installed

Checking dependencies...
I cannot create the folder!
The folder /home/earnest/CRISPResso_dependencies is not empty!
CHECKING DEPENDENCIES...
flash is already installed!
needle is already installed!
All done!%

**Comment by lucapinello** [comment]
It looks good to me, now it should run fine...

If not check  few things:

1) Are you in the correct conda env? (i.e. source activate py27 )
2) Check if you have something weird in your PATH or PYTHONPATH env variables.
3) try to run:

which CRISPResso

You should get something like this:

~/anaconda2/envs/py27/bin/CRISPResso

If not I guess docker is the fastest way to get CRISPResso up and running.

Best,

Luca

**Comment by strohmjeff** [comment]
Thanks for your help Luca,

I'm just using the web version for now. It worked great for some 250PE read datasets that I have. I'm now working on a 75bp single-end analysis, and the web version rejects my data with the "unable to align any reads to reference"

I have attached a screenshot from IGV showing how the reads align to the reference. I have tried both the full 800bp region and a 230bp  region in which the editing is taking place. Can you see anything wrong with my input? I've been filtering my read files with samtools to only include reads mapped to the region I'm interested in. 

![igv_screenshot](https://user-images.githubusercontent.com/33067918/32959637-175c16b8-cb77-11e7-946b-1a5455f04c39.png)

>T2_reference
TTTCCACACACTTTTGGGTATTCTCTCCCTTTTTCTTTCAACCCAAAGTTCACCACTGACCATCCCACCCTCATCCCCCCTCCTGGTGGACGGTGCGGTACAGTGTGGGGCACTGAGCCAAGGCCAGCACCCCCGGGCCGCTGTGTGGACTCCATCCTGCCAATCCCACATTGGCGTGGTGCATCTCCCCATTCCTCCTTGGGCTGCATGGGGGTGCCCCTGGAGGCCTTGGCTCAATGCAAGGCTCCTTGGGACAGCTCTGGGAGGTGACAAGACCCCACCCTTCTGCTGCAGGAGCAGGTCCTAGGACTTTGGTTGTGGTCTGTCTGGGCTCCTTCATTTCTGCAGGGGACCCTGGGTGTTAGCAAGTAGCAGCAACACCACAGTTTCCCCTCCTGCACTGGACCCCAGTTGTGCTCAGGTAGCCAGCCCTCCATCCAGGGCCCCTGACTGCTCTCTTCTCTTCTGCCAGCTATAGTGACCTTAGTGATCCCTCCGGGTGGATGGTCCAGTTTGGCCAGCTGACTTCCATGCCATCCTTCTGGAGCCTGCAGGCCTACTACACCCGTTACTTCGTATCGAATATCTATCTGAGCCCTCGCTACCTGGGGAATTCACCCTATGACATTGCCTTGGTGAAGCTGTCTGCACCTGTCACCTACACTAAACACATCCAGCCCATCTGTCTCCAGGCCTCCACATTTGAGTTTGAGAACCGGACAGACTGCTGGGTGACTGGCTGGGGGTACATCAAAGAGGATGAGGGTGAGGCTGGGGACAGGCGGGTCAGGGAGGAACTGTCTTTGTTCACCTGTTCCCC

**Comment by lucapinello** [comment]
It seems your reads are not overlapping. In this case unfortunately you cannot use CRISPResso.

**Comment by strohmjeff** [comment]
Got it, thanks for your quick reply
