### ISSUE TITLE
Error "'numpy.int64'

### ISSUE THREAD

**Issue by amarcog** [lucapinello/CRISPResso#34]
Hello @lucapinello ,

I am trying to run CRISPResso locally to genotype clonal cell lines. It stops at two different points depending of the input:

Error 1:  "Quantifying indels/substitutions... " reporting:

ERROR: Zero sequences aligned, please check your amplicon sequence 

[CRISPResso_RUNNING_LOG_Zero_error.txt](https://github.com/lucapinello/CRISPResso/files/1688674/CRISPResso_RUNNING_LOG_Zero_error.txt)

or Error 2: "Calculating alleles frequencies... " reporting:

("'numpy.int64' object is not iterable", u'occurred at index 0')

[CRISPResso_RUNNING_LOG_numpy.int64_error.txt](https://github.com/lucapinello/CRISPResso/files/1688673/CRISPResso_RUNNING_LOG_numpy.int64_error.txt)

Could be related with a low quality input fastq file? 

I don't think that is a problem in the installation because I properly ran CRISPResso locally with successful results using fastq files with higher quality. 

I would like to send you an example of both files (those than worked and current ones) in order to know if you are able to detect the difference that avoids CRISPResso to run properly. The problem is that I can't attach them because they are so big.

Running machine: Mac (OSX El Captain)

Thank you so much for your attention,

Andrés Marco

**Comment by bonobo97** [comment]
Hi,
I had the same problem. I think the problem might be that your paired end reads do not overlap in the middle, which is expected by the algorithm. Are you running single end or paired end?
Bence

**Comment by lucapinello** [comment]
Thanks @bonobo97 !
@amarcog did you check if your reads overlap as suggested by @bonobo97 ?

**Comment by bdoughty** [comment]
I'm having this error too, using single end reads with version 1.0.10. It will work on some loci, but on others it gets to calculating allele frequencies and shows the same error. Since it works at some places and not at others I assume it's something on my end, but I was wondering if you had any suggestions. 

Thanks, 
Ben

**Comment by lucapinello** [comment]
Hey Ben,

Can you share with us the input files and the complete output folder for
one experiment that failed to run?

Thanks,

Luca

**Comment by bonobo97** [comment]
Hi Luca,
I think I don’t have them anymore. I’m just learning how to do NGS analysis (in general) and I did not keep a nice track of what was happening. But I’m sure the problem was having too long reads that could not be merged with flash. Instead of specific messages, it was complaining about numpy. I just ran it in single end mode and it was fine.
I could try to find the original file and run it. Let me know!
Bence

**Comment by bdoughty** [comment]
Hi Luca, thanks for the prompt response! Attached are the input fastq and a zip of the output directory. The command I ran was:

CRISPResso -r1 1-F3_S63_L001_R2_001.fastq.gz -a GAGGGCTGGGCGTTATCCTAGGCAGCAGAGCCGGGCGGTTACCCCGATGCTTGGGGGAGGTGGTAGAGGGGTCTGGGACCAAGGAATAGCGAGGCCCCTCTTAGCGGGGGGCCCTGGTATACACAGAGGCTCAGATGGTGGACTAGATTTTCTGAAGCATATAACTCATTGTTCCTTGTGTTCCAGTTTGGGTAGATCGG -g AGAGCCGGGCGGTTACCCCG --cleavage_offset -10

Note, I had other samples at the same locus that I got this command to run successfully on. There were other loci where none of the commands worked, although I'm pretty sure that everything was input right. Thanks for your help and a convenient tool!

Ben

[CRISPResso_on_1-F3_S63_L001_R2_001.zip](https://github.com/lucapinello/CRISPResso/files/1989561/CRISPResso_on_1-F3_S63_L001_R2_001.zip)
[1-F3_S63_L001_R2_001.fastq.gz](https://github.com/lucapinello/CRISPResso/files/1989564/1-F3_S63_L001_R2_001.fastq.gz)

Edit: I wonder if read quality could be an issue? I noticed a distinct worsening of base quality after ~100bp of sequencing.

**Comment by kclem** [comment]
Errors producing "("'numpy.int64' object is not iterable", u'occurred at index 0')" have been resolved in version 1.0.11. Please update and try again. #40
