### ISSUE TITLE
Front End Code

### ISSUE THREAD

**Issue by ksindy** [lucapinello/CRISPResso#35]
Hello,
I love your tool, it is very well done. Would it be possible to provide the Front End code that is running on http://crispresso.rocks/ 
Thanks!
Karly

**Comment by lucapinello** [comment]
Hi Karly,

Thanks!

It will get released with the new version of CRISPResso2 (my university is
updating the licensing terms).

Stay tuned.

Best,

Luca

**Comment by ksindy** [comment]
Awesome! Any idea when that might be?

**Comment by lucapinello** [comment]
Probably 1-2 months.

**Comment by ksindy** [comment]
Thanks!
