### ISSUE TITLE
FLASH: Low Percent Combined

### ISSUE THREAD

**Issue by Transmystical** [lucapinello/CRISPResso#37]
Greetings! 

I have Illumina NextSeq500 150bp, paired end reads, generated from whole shotgun sequencing of environmental samples. These sequences have been quality filtered (Sickle, Phred > 20, default length to keep a read = 20bp). I am now trying to use FLASH to merge the paired end reads. For all of my metagenomes, I get really low numbers (as compared to the FLASH website and paper). 

I ran the  command as follows for all metagenomes: 
./flash -M 150  -o Flash.out Forward.fastq Reverse.fastq | tee Flash.log

The range of Percent combined: Min = 13.04% ; Max = 52.72% ; Ave = 32.11% 

I am curious as to why these numbers are so low or if this is considered to be "acceptable." 

Many Thanks!!

**Comment by lucapinello** [comment]
Hi Transmystical, we don't provide support for FLASH in general since in CRISPResso it is used to merge overlapping reads from amplicon sequencing. So I would suggest you contact the authors of FLASH for your specific application.

**Comment by Transmystical** [comment]
Thank you!
