### ISSUE TITLE
CRIPRessoPooled - query

### ISSUE THREAD

**Issue by frankbioinfo** [lucapinello/CRISPResso#38]
Hello once again @lucapinello 

Sorry to bug you again, I am using CrispressoPooled to analyze some pooled amplicon data

My experimental  set up, 

Paired end seq, 4 samples, 6 amplicons and 6 guides, i prepared the description file as mention in the docs had few questions 

1) it the pooled analysis limited to only 5 amplicons? 
"A description file containing the amplicon sequences used to enrich regions in the genome and some additional information. In particular, this file, is a tab delimited text file with up to 5 columns (first 2 columns required):"

2) Also i see this error "Skipping amplicon [site4] since no reads are aligning to it" all the other (5 of them) amplicons produce results as expected except site4, to add further I use the this amplicon and guide and process it using (the same fastq files) only CRISPResso.py and it seems to work fine was wondering what am i missing.  Note i am using default parameters for both the analysis.

Thanks a ton once again. 

Frank

**Comment by lucapinello** [comment]
1. Each amplicon is on a different row not columns
2. It may be an artifact of the demultiplexing if you are amplicons are not distinct
