### ISSUE TITLE
Run for a long times

### ISSUE THREAD

**Issue by tiramisutes** [lucapinello/CRISPResso#41]
Hi,
I use the CRISPResso with a Single-Read as follows command.
```
CRISPResso -r1 sample_R1_001.fastq.gz -a ATATGACCAGGTCGTACACGATGTGGATCTGCAGAAGCTGCCTGTAAGATTTGCAATGGACAGAGCTGGCCTCGTTGGTGCAGATGGTCCAACACATTGTGGGGCTTTTGATGTCACTTTCATG -g TTGGTGCAGATGGTCCAACACAT --name sample -o ${out} --trim_sequences -p ${cpu} -w 20
```
But It's still in the step "Calculating alleles frequencies" when running long times.
```
INFO  @ Thu, 31 May 2018 14:15:20:
	 Calculating alleles frequencies... 
```
So, whether the CRISPResso is supporting for Single-Read? And what is the best way for the Single-Read sequence?

**Comment by lucapinello** [comment]
Yes we support single-read.

How big is your dataset (#reads) and how many cpu are you using?

**Comment by tiramisutes** [comment]
The single-read is total size 612M in the compressed format (sample.fq.gz) and I use 20 CPU.

**Comment by lucapinello** [comment]
Hi Hope,
This is much bigger than our usual samples. Unfortunately, there is not much more you can do to speedup CRISPResso. We are working on a new version of CRISPResso that is ~10X faster, this may be a solution to your problem. We should have a first version ready in about 2-3 weeks.
