### ISSUE TITLE
Error while generating plots with Cpf1 data

### ISSUE THREAD

**Issue by dfajar2** [lucapinello/CRISPResso#44]
I have been using CRIPResso with Cas9 and Cpf1. So far, all the Cas9 experiments are fine, but when I ran the Cpf1 I get an error when generating the plots. I should say that the plots 1a, 1b, 2, 3, 4a, 4b, and 4e are generated. It seems to fail while generating plot 9.  BTW I am specifying "--guide_seq" and also "--cleavage_offset 1" when running Cpf1. 

Here's the last section of the log file:
....
INFO  @ Thu, 28 Jun 2018 14:53:51:
         Calculating alleles frequencies...

INFO  @ Thu, 28 Jun 2018 14:55:38:
         Done!

INFO  @ Thu, 28 Jun 2018 14:55:38:
         Making Plots...

CRITICAL @ Thu, 28 Jun 2018 14:55:49:
         Unexpected error, please check your input.

ERROR: 'N'

**Comment by lucapinello** [comment]
Hi there,

Thanks for using CRISPResso.

Which version are you using?

Do you have many reads with 'N' in this sample?

Can you share with us the fastq files and the full report?

Thanks,

**Comment by dfajar2** [comment]
Sure  here they are. 
I thought it was the Ns in the reads, but there doesn't seem to be a problem with the Ns with the Cas9s.
Thanks

[CRISPResso_RUNNING_LOG.txt](https://github.com/lucapinello/CRISPResso/files/2150817/CRISPResso_RUNNING_LOG.txt)

[13-Cpf1-38337AS_S13_L001_R1_001.fastq.gz](https://github.com/lucapinello/CRISPResso/files/2150818/13-Cpf1-38337AS_S13_L001_R1_001.fastq.gz)
[13-Cpf1-38337AS_S13_L001_R2_001.fastq.gz](https://github.com/lucapinello/CRISPResso/files/2150819/13-Cpf1-38337AS_S13_L001_R2_001.fastq.gz)

Here are also the amplicon and guide sequences

-a tccatttcatagtctttccttgggtgtgttaaaagtgaccatggtacactcagcacggatgaaatgaaacagtgtttagaaacgtcagtcttctcttttgtaatgccctgtagtctctctgtatgttatatgtcacattttgtaattaacagcttgctggtgaaaaggaccccacgaagtgttggatataagccagactgtaagtgaattactttttttgtcaatcatttaaccatctttaacctaaaagagttttatgtgaaatggcttataattgcttagagaatatttg -g GGTTAAAGATGGTTAAATGAT

**Comment by lucapinello** [comment]
Fixed with Version 1.0.13!

The problem was that we never had a sample with most common alleles with N. 

Please let me know how it goes.

**Comment by dfajar2** [comment]
thanks!!! I'll give it a try.
