### ISSUE TITLE
[FLASH] ERROR: Maximum overlap (-173) cannot be less than the minimum overlap (4).

### ISSUE THREAD

**Issue by hffqyd** [lucapinello/CRISPResso#45]
Hi:

Thanks for the wonderful tool! But when I used it to evaluate the sgRNA indel with the following script:

    CRISPResso -r1 1.fq.gz -r2 2.fq.gz -a amplicon_sequence

there was an error "[FLASH] ERROR: Maximum overlap (-173) cannot be less than the minimum overlap (4)." It seemed that 'flash' failed to align when there was paired reads didn't cover the amplicon. Is that right? What should I do for this error? Thank you very much!

**Comment by lucapinello** [comment]
Hi,

Thanks!

Yes, unfortunately we don't support non-overlapping reads.

If your cleavage site position+-20 bp is fully inside one of the two reads, you can run CRISPResso in single read mode.

But for optimal quantification, we advise having overlapping reads that possibly span the indels.

Best,

Luca
