### ISSUE TITLE
modify the python scripts for availability to other CRISPR systems

### ISSUE THREAD

**Issue by tiramisutes** [lucapinello/CRISPResso#47]
Hi,
This program is best for analysis of conventional Cas9 (20bp+NGG) genome-editing sequencing data. But I also want to use this program to analysis cpf1(TTTN+23bp) sequencing data. So, I need to modify the source python scripts to instead the NGG to TTTN and other contents. The scripts `CRISPRessoCORE.py`  is complicated and I can not find how to change. 
So, can you give some hints?
Thanks.

**Comment by lucapinello** [comment]
Hi, as stated in the documentation this can be accomplished using the option:

--cleavage_offset: This parameter allows for the specification of the cleavage offset to use with respect to the provided sgRNA sequence. Remember that the sgRNA sequence must be entered without the PAM. The default is -3 and is suitable for the SpCas9 system. **For alternate nucleases, other cleavage offsets may be appropriate, for example, if using Cpf1 set this parameter to 1.** (default: -3, minimum:1, max: reference amplicon length). Note: any large indel that partially overlap the window will be also fully quantified.
