### ISSUE TITLE
Left-aligning option

### ISSUE THREAD

**Issue by dfajar2** [lucapinello/CRISPResso#48]
Hi Luca,

First of all thanks for developing this pipeline. 

I have a question for you. I'm pasting below two of the alleles from the "Alleles_frequency_table_around_cut_site" file.

Aligned_Sequence	Reference_Sequence	Unedited	%Reads	#Reads
GACTGTAAGTGAATTACTTTTTTTGTCAATCA----ACCATCTTTAACCTAAAAGAGTTT	GACTGTAAGTGAATTACTTTTTTTGTCAATCATTTAACCATCTTTAACCTAAAAGAGTTT	True	0.24111800019683108	49
GACTGTAAGTGAATTACTTTTTTTGTCAATC----AACCATCTTTAACCTAAAAGAGTTT	GACTGTAAGTGAATTACTTTTTTTGTCAATCATTTAACCATCTTTAACCTAAAAGAGTTT	True	0.16730636748351543	34

As you can see, they are exactly the same except for the A which can align to either side. This reminds me to the LeftAlignAndTrimVariants module from GATK which in cases like this, simplifies the output by aligning those bases always to the left. Is it possible to improve the alignment in CRISPResso, so they are grouped as the same event?

Thanks

**Comment by lucapinello** [comment]
Right, this is a common problem associated with the needle alignment program we have used in CRISPResso. We have a new version of CRISPResso2 with our custom alignment to test here: crispresso2.pinellolab.org Could you please let us know if you also observe the same problem with this new version?

**Comment by dfajar2** [comment]
Will do and thanks again

**Comment by dfajar2** [comment]
Just to let you know that I just tested CRISPResso2 and it fixes this alignment problem. Is the code publicly available yet?

**Comment by lucapinello** [comment]
Great, not yet we are finalizing it before publication, for now, please use
the website and please let us know if you encounter any problems.

**Comment by dfajar2** [comment]
Perfect. 
Thanks!

**Comment by cdustinr** [comment]
Great! Really looking forward to release of v2!!

**Comment by lucapinello** [comment]
Now it is available https://github.com/pinellolab/crispresso2
