### ISSUE TITLE
Running failed with the example sequences

### ISSUE THREAD

**Issue by MagpiePKU** [lucapinello/CRISPResso#5]
Environment: CentOS6.5, Python 2.7.11, CRISPResso installed from source (master.zip downloaded from github), needle, flash and trimmomatic are in the CRISPResso dependencies dir. 

Data was downloaded from http://bcb.dfci.harvard.edu/~lpinello/CRISPResso as indicated and run as:

CRISPResso -r1 reads1.fastq.gz -r2 reads2.fastq.gz -a AATGTCCCCCAATGGGAAGTTCATCTGGCACTGCCCACAGGTGAGGAGGTCATGATCCCCTTCTGGAGCTCCCAACGGGCCGTGGTCTGGTTCATCATCTGTAAGAATGGCTTCAAGAGGCTCGGCTGTGGTT -g TGAACCAGACCACGGCCCGT

output as follows:

``` CRISPResso~~~
-Analysis of CRISPR/Cas9 outcomes from deep sequencing data-

                      )
                     (
                    __)__
                 C\|     \
                   \     /
                    \___/


[Luca Pinello 2015, send bugs, suggestions or *green coffee* to lucapinello AT gmail DOT com]

Version 0.9.8

INFO  @ Tue, 02 Aug 2016 17:32:39:
     Cut Points from guide seq:[76]

WARNING @ Tue, 02 Aug 2016 17:32:39:
     Folder CRISPResso_on_reads1_reads2 already exists.

INFO  @ Tue, 02 Aug 2016 17:32:39:
     Estimating average read length...

INFO  @ Tue, 02 Aug 2016 17:32:40:
     Merging paired sequences with Flash...

INFO  @ Tue, 02 Aug 2016 17:32:41:
     Done!

INFO  @ Tue, 02 Aug 2016 17:32:42:
     Preparing files for the alignment...

INFO  @ Tue, 02 Aug 2016 17:32:42:
     Done!

INFO  @ Tue, 02 Aug 2016 17:32:42:
     Aligning sequences...

sed: couldn't write 73 items to stdout: Broken pipe
awk: (FILENAME=- FNR=809) fatal: print to "standard output" failed (Broken pipe)

gzip: stdout: Broken pipe
cat: write error: Broken pipe
INFO  @ Tue, 02 Aug 2016 17:32:42:
     Quantifying indels/substitutions...

CRITICAL @ Tue, 02 Aug 2016 17:32:42:
     Alignment error, please check your input.

ERROR: Zero sequences aligned, please check your amplicon sequence

```

**Comment by lucapinello** [comment]
Hi,
thanks for reporting this problem.

Can you send me the content of the folder after the program fail?

Also san you check few things for me?

1) Can you try to run the example in a new folder?
2) Do you have needle and flash in your path?
3)Are you using a network drive for the output?

Thanks!

**Comment by MagpiePKU** [comment]
1. Tried that after your suggestion -- did not work either. The error msg was somewhat different in 'awk (FILENAME=- FNR=2841)' but other things are similar. 
2. Yes, needle and flash are in path and usable (checked)
3. Originally the drive was GPFS but I tried moving it to local drive, worked (magically). Why was that? 

Thanks again.

**Comment by aaiezza** [comment]
@MagpiePKU I've actually received that error before too. I think it is related to reads not being able to map to any given amplicons; which in my case was because of a file permissions issue across to a cifs shared folder. You might try checking for file permissions, especially on any generated files.

**Comment by lucapinello** [comment]
Thanks for the quick reply.

Alex also thanks to your comment.

I think that additionaly to the permission problem mentioned by Alex another problem may be that some network drive implementation return the control to the app too fast even if a file is not fully written. The problem is that there is not easy way to check with an high level call if the file is fully synced before proceeding with the other command in the pipeline.

**Comment by pankajki** [comment]
Running CRISPResso on region #1/18227: /home/pankum/miniconda3/lib/python2.7/site-packages/CRISPResso.py -r1 /san/ongoing/CRISPER_WGS_Data/CRISpresso/B2M-KO_101_predicted/CRISPRessoWGS_on_B2M-KO_101_predicted/ANALYZED_REGIONS/REGION_R_1.fastq.gz -a catctctctagggcaacgtcggctgcagctgagatggctgctccccggtg -o /san/ongoing/CRISPER_WGS_Data/CRISpresso/B2M-KO_101_predicted/CRISPRessoWGS_on_B2M-KO_101_predicted --name R_1 --needleman_wunsch_gap_extend -2 --max_rows_alleles_around_cut_to_plot 50 --aln_seed_count 5 --needleman_wunsch_aln_matrix_loc EDNAFULL --quantification_window_size 1 --quantification_window_center -3 --trimmomatic_command trimmomatic --conversion_nuc_from C --min_bp_quality_or_N 0 --default_min_aln_score 60 --needleman_wunsch_gap_incentive 1 --plot_window_size 40 --aln_seed_min 2 --needleman_wunsch_gap_open -20 --aln_seed_len 10 --conversion_nuc_to T --min_single_bp_quality 0 --exclude_bp_from_left 15 --min_average_read_quality 0 --min_frequency_alleles_around_cut_to_plot 0.2 --exclude_bp_from_right 15
CRISPResso command failed (return value 127) on region #0: "/home/pankum/miniconda3/lib/python2.7/site-packages/CRISPResso.py -r1 /san/ongoing/CRISPER_WGS_Data/CRISpresso/B2M-KO_101_predicted/CRISPRessoWGS_on_B2M-KO_101_predicted/ANALYZED_REGIONS/REGION_R_1.fastq.gz -a catctctctagggcaacgtcggctgcagctgagatggctgctccccggtg -o /san/ongoing/CRISPER_WGS_Data/CRISpresso/B2M-KO_101_predicted/CRISPRessoWGS_on_B2M-KO_101_predicted --name R_1 --needleman_wunsch_gap_extend -2 --max_rows_alleles_around_cut_to_plot 50 --aln_seed_count 5 --needleman_wunsch_aln_matrix_loc EDNAFULL --quantification_window_size 1 --quantification_window_center -3 --trimmomatic_command trimmomatic --conversion_nuc_from C --min_bp_quality_or_N 0 --default_min_aln_score 60 --needleman_wunsch_gap_incentive 1 --plot_window_size 40 --aln_seed_min 2 --needleman_wunsch_gap_open -20 --aln_seed_len 10 --conversion_nuc_to T --min_single_bp_quality 0 --exclude_bp_from_left 15 --min_average_read_quality 0 --min_frequency_alleles_around_cut_to_plot 0.2 --exclude_bp_from_right 15"

**Comment by pankajki** [comment]
Programme terminated with following error message

Running CRISPResso on region #1/18227: /home/pankum/miniconda3/lib/python2.7/site-packages/CRISPResso.py -r1 /san/ongoing/CRISPER_WGS_Data/CRISpresso/B2M-KO_101_predicted/CRISPRessoWGS_on_B2M-KO_101_predicted/ANALYZED_REGIONS/REGION_R_1.fastq.gz -a catctctctagggcaacgtcggctgcagctgagatggctgctccccggtg -o /san/ongoing/CRISPER_WGS_Data/CRISpresso/B2M-KO_101_predicted/CRISPRessoWGS_on_B2M-KO_101_predicted --name R_1 --needleman_wunsch_gap_extend -2 --max_rows_alleles_around_cut_to_plot 50 --aln_seed_count 5 --needleman_wunsch_aln_matrix_loc EDNAFULL --quantification_window_size 1 --quantification_window_center -3 --trimmomatic_command trimmomatic --conversion_nuc_from C --min_bp_quality_or_N 0 --default_min_aln_score 60 --needleman_wunsch_gap_incentive 1 --plot_window_size 40 --aln_seed_min 2 --needleman_wunsch_gap_open -20 --aln_seed_len 10 --conversion_nuc_to T --min_single_bp_quality 0 --exclude_bp_from_left 15 --min_average_read_quality 0 --min_frequency_alleles_around_cut_to_plot 0.2 --exclude_bp_from_right 15
CRISPResso command failed (return value 127) on region #0: "/home/pankum/miniconda3/lib/python2.7/site-packages/CRISPResso.py -r1 /san/ongoing/CRISPER_WGS_Data/CRISpresso/B2M-KO_101_predicted/CRISPRessoWGS_on_B2M-KO_101_predicted/ANALYZED_REGIONS/REGION_R_1.fastq.gz -a catctctctagggcaacgtcggctgcagctgagatggctgctccccggtg -o /san/ongoing/CRISPER_WGS_Data/CRISpresso/B2M-KO_101_predicted/CRISPRessoWGS_on_B2M-KO_101_predicted --name R_1 --needleman_wunsch_gap_extend -2 --max_rows_alleles_around_cut_to_plot 50 --aln_seed_count 5 --needleman_wunsch_aln_matrix_loc EDNAFULL --quantification_window_size 1 --quantification_window_center -3 --trimmomatic_command trimmomatic --conversion_nuc_from C --min_bp_quality_or_N 0 --default_min_aln_score 60 --needleman_wunsch_gap_incentive 1 --plot_window_size 40 --aln_seed_min 2 --needleman_wunsch_gap_open -20 --aln_seed_len 10 --conversion_nuc_to T --min_single_bp_quality 0 --exclude_bp_from_left 15 --min_average_read_quality 0 --min_frequency_alleles_around_cut_to_plot 0.2 --exclude_bp_from_right 15"

**Comment by lucapinello** [comment]
Can you please try with the new version of CRISPREsso available here:
https://github.com/pinellolab/crispresso2  ?

Thanks,

Luca

**Comment by pankajki** [comment]
I used your new version Crispresso2 and then terminated..

**Comment by pankajki** [comment]
CRISPresso version 2.0.23

**Comment by lucapinello** [comment]
OK please open an issue there with the full report so we can take a look.

**Comment by pankajki** [comment]
ok
