### ISSUE TITLE
Appears to be counting reads with deletions as unedited 

### ISSUE THREAD

**Issue by AGRaeside** [lucapinello/CRISPResso#50]
Hi Luca,
Big fan of crispresso and very much looking forward to crispresso 2.
I was running a batch of crispressos and I came across a few wells that seems to have a usually high amount of unmodified reads. When i looked at the alleles around the predicted cut side they appeared to have clear deletions but were counted as unmodified in every statistic.

Aligned_Sequence	Reference_Sequence	Unedited	%Reads	#Reads
AGTGGAGGATGCCTTCT--ACGTTGGTGCGTGAGATCCGG	AGTGGAGGATGCCTTCTACACGTTGGTGCGTGAGATCCGG	True	61.50844322453524	103082
GATGCCTTC-ACATGTCTCACGTTGGTGCGTGAGATCCGG	GATGCCTTCTA-------CACGTTGGTGCGTGAGATCCGG	True	35.92815800465359	60212
AGTGGAGGATGCCTTCT-----------------------	AGTGGAGGATGCCTTCTACACGTTGGTGCGTGAGATCCGG	False	0.6533802732859946	1095

I'm not sure why it CRISPresso could be counting these reads as unmodified. I think there is the same thing in the reads in the left-aligning option issue where the reads have deletions but are counted as unedited. 

Any help would be deeply appreciated.

Thanks,

Alexander Raeside 
Oxford Genetics

**Comment by lucapinello** [comment]
This depends on the window size you have set around the cleavage site. If those indels are not overlapping the window they will not be counted.
