### ISSUE TITLE
Last stage error Error with FLASH for CRISPRessoPooled.py  

### ISSUE THREAD

**Issue by bilalSarwar2020** [lucapinello/CRISPResso#51]
Dear Luca Pinello
I am using CRISPRessoPooled.py script to analyzed the paired ends reads data by Illumina. 
the read length is 150 bp.
the amplicon size is 180bp long.
below is the command that I am used several time.
it ends up with an error at last of the analysis 
I am new to the Linux environment. Kindly help me to resolve this issue.
thanks  
**ERROR: Flash failed to run, please check the log file.** 

$ python CRISPRessoPooled.py -r1 /home/bilal/Sir_Qayyum_data/6297_1_1.fastq.gz -r2 /home/bilal/Sir_Qayyum_data/6297_1_2.fastq.gz  -f /home/bilal/Sir_Qayyum_data/CRISPResso-master/cat.csv 
  
~~~CRISPRessoPooled~~~
-Analysis of CRISPR/Cas9 outcomes from POOLED deep sequencing data-

              )                                            )
             (           _______________________          (
            __)__       | __  __  __     __ __  |        __)__
         C\|     \      ||__)/  \/  \|  |_ |  \ |     C\|     \
           \     /      ||   \__/\__/|__|__|__/ |       \     /
            \___/       |_______________________|        \___/
        

[Luca Pinello 2015, send bugs, suggestions or *green coffee* to lucapinello AT gmail DOT com]

Version 1.0.13

INFO  @ Tue, 05 Feb 2019 22:43:54:
	 Checking dependencies... 

INFO  @ Tue, 05 Feb 2019 22:43:54:
	 
 All the required dependencies are present! 

INFO  @ Tue, 05 Feb 2019 22:43:54:
	 Only the Amplicon description file was provided. The analysis will be perfomed using only the provided amplicons sequences. 

INFO  @ Tue, 05 Feb 2019 22:43:54:
	 Creating Folder CRISPRessoPooled_on_6297_1_1_6297_1_2 

WARNING @ Tue, 05 Feb 2019 22:43:54:
	 Folder CRISPRessoPooled_on_6297_1_1_6297_1_2 already exists. 

INFO  @ Tue, 05 Feb 2019 22:43:54:
	 Merging paired sequences with Flash... 

CRITICAL @ Tue, 05 Feb 2019 22:43:54:
	 

ERROR: Flash failed to run, please check the log file.

**Comment by lucapinello** [comment]
Can you send us the log file?

Also can you please try with the new version of CRISPREsso available here:
https://github.com/pinellolab/crispresso2

**Comment by bilalSarwar2020** [comment]
Dear Luca Pinello
Thanks for getting me back. Probably the FLASH was not at the right PATH. I got a clue from your response to issue #49 and after fixing it run successfuly but with the empty output files in the result folder. i attached all the files including the log files.
kindly help me 

Regards 
stressed   






. 
[CRISPRessoPooled_RUNNING_LOG.txt](https://github.com/lucapinello/CRISPResso/files/2837017/CRISPRessoPooled_RUNNING_LOG.txt)
[MAPPING_STATISTICS.txt](https://github.com/lucapinello/CRISPResso/files/2837018/MAPPING_STATISTICS.txt)
[REPORT_READS_ALIGNED_TO_AMPLICONS.txt](https://github.com/lucapinello/CRISPResso/files/2837019/REPORT_READS_ALIGNED_TO_AMPLICONS.txt)
[SAMPLES_QUANTIFICATION_SUMMARY.txt](https://github.com/lucapinello/CRISPResso/files/2837020/SAMPLES_QUANTIFICATION_SUMMARY.txt)

**Comment by lucapinello** [comment]
Do you have bowtie2 installed and in the path?

**Comment by bilalSarwar2020** [comment]
YES Version 2.2.6 installed 


bilal@Plant-Genomics:~$ bowtie2 --version
/usr/bin/bowtie2-align-s version 2.2.6
64-bit
Built on lgw01-12
Mon Dec 28 11:09:46 UTC 2015
Compiler: gcc version 5.3.1 20151219 (Ubuntu 5.3.1-4ubuntu1) 
Options: -O3 -m64 -msse2  -funroll-loops -g3 -Wl,-Bsymbolic-functions -Wl,-z,relro -DPOPCNT_CAPABILITY -DWITH_TBB
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}

**Comment by lucapinello** [comment]
Can you please try with the new version of CRISPResso and install it via
conda?


See the instructions here: https://github.com/pinellolab/crispresso2
