### ISSUE TITLE
CRISPResso command failed (return value 127) on region #0:

### ISSUE THREAD

**Issue by pankajki** [lucapinello/CRISPResso#52]
Using Crespresso 2.0.23
CRISPRessoWGS terminated with following error message:
Total region analyzed 18227
Similar message for all 18227 regions.
Running CRISPResso on region #1/18227: /home/pankum/miniconda3/lib/python2.7/site-packages/CRISPResso.py -r1 /san/ongoing/CRISPER_WGS_Data/CRISpresso/B2M-KO_101_predicted/CRISPRessoWGS_on_B2M-KO_101_predicted/ANALYZED_REGIONS/REGION_R_1.fastq.gz -a catctctctagggcaacgtcggctgcagctgagatggctgctccccggtg -o /san/ongoing/CRISPER_WGS_Data/CRISpresso/B2M-KO_101_predicted/CRISPRessoWGS_on_B2M-KO_101_predicted --name R_1 --needleman_wunsch_gap_extend -2 --max_rows_alleles_around_cut_to_plot 50 --aln_seed_count 5 --needleman_wunsch_aln_matrix_loc EDNAFULL --quantification_window_size 1 --quantification_window_center -3 --trimmomatic_command trimmomatic --conversion_nuc_from C --min_bp_quality_or_N 0 --default_min_aln_score 60 --needleman_wunsch_gap_incentive 1 --plot_window_size 40 --aln_seed_min 2 --needleman_wunsch_gap_open -20 --aln_seed_len 10 --conversion_nuc_to T --min_single_bp_quality 0 --exclude_bp_from_left 15 --min_average_read_quality 0 --min_frequency_alleles_around_cut_to_plot 0.2 --exclude_bp_from_right 15
CRISPResso command failed (return value 127) on region #0: "/home/pankum/miniconda3/lib/python2.7/site-packages/CRISPResso.py -r1 /san/ongoing/CRISPER_WGS_Data/CRISpresso/B2M-KO_101_predicted/CRISPRessoWGS_on_B2M-KO_101_predicted/ANALYZED_REGIONS/REGION_R_1.fastq.gz -a catctctctagggcaacgtcggctgcagctgagatggctgctccccggtg -o /san/ongoing/CRISPER_WGS_Data/CRISpresso/B2M-KO_101_predicted/CRISPRessoWGS_on_B2M-KO_101_predicted --name R_1 --needleman_wunsch_gap_extend -2 --max_rows_alleles_around_cut_to_plot 50 --aln_seed_count 5 --needleman_wunsch_aln_matrix_loc EDNAFULL --quantification_window_size 1 --quantification_window_center -3 --trimmomatic_command trimmomatic --conversion_nuc_from C --min_bp_quality_or_N 0 --default_min_aln_score 60 --needleman_wunsch_gap_incentive 1 --plot_window_size 40 --aln_seed_min 2 --needleman_wunsch_gap_open -20 --aln_seed_len 10 --conversion_nuc_to T --min_single_bp_quality 0 --exclude_bp_from_left 15 --min_average_read_quality 0 --min_frequency_alleles_around_cut_to_plot 0.2 --exclude_bp_from_right 15"

**Comment by lucapinello** [comment]
You need to open the issue under:  https://github.com/pinellolab/crispresso2
