### ISSUE TITLE
Longer Allele Sequences

### ISSUE THREAD

**Issue by amarcog** [lucapinello/CRISPResso#53]
Hello Luca,

Is there any way to have longer allele sequences in the file Alleles_frequency_table_around_cut_site_for_*.txt?

It would be useful for the analysis of HDR events that are located far away from the gRNA cutting site.

Thank you for your attention,

Andrés

**Comment by lucapinello** [comment]
Yes there is a flag for the command line you can set to have larger
alleles. BTW we have a new version of crispresso i.e. Crispresso2. This
version is now depracated and not supported anymore.

**Comment by amarcog** [comment]
Thank you for your answer.

I don't find this flag, is it only available in CRISPResso2? Maybe is --window_around_sgrna?
I'm using this version because we want to be consistant with a big amount of old data that was already analyzed with CRISPResso1. But for sure in next experiments I will use the new version.

Than you again for your attention

Andrés

**Comment by lucapinello** [comment]
Andres,

This is the option:

--offset_around_cut_to_plot  'Offset to use to summarize alleles around the cut site in the alleles table plot.'  default=20

Best,

Luca

**Comment by amarcog** [comment]
Thank you!

Andrés

De: Luca Pinello <notifications@github.com>
Responder a: lucapinello/CRISPResso <reply@reply.github.com>
Fecha: viernes, 17 de mayo de 2019, 15:47
Para: lucapinello/CRISPResso <CRISPResso@noreply.github.com>
CC: amarcog <andresmg1993@gmail.com>, Author <author@noreply.github.com>
Asunto: Re: [lucapinello/CRISPResso] Longer Allele Sequences (#53)


Andres,

This is the option:

--offset_around_cut_to_plot 'Offset to use to summarize alleles around the cut site in the alleles table plot.' default=20

Best,

Luca
