### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by magniff** [lucapinello/CRISPResso#8]
Is this thing even working? Who knows) I think it is time to add some tests.

**Comment by lucapinello** [comment]
magniff, thanks for your feedback, we provided some examples data to test the pipeline in your machine in the docs but not automating testing. CRISPResso has been tested on OSX, Centos >5 and Ubuntu >14.04.

**Comment by magniff** [comment]
So you are not planning to provide any unit tests, right?)

**Comment by lucapinello** [comment]
The tests to check the validity of the pipeline are provided in the
supplementary material of the paper (see the simulation section and the
ipython notebooks to check the reproducibility of our results)

In the current version we don't have an automatic testing suite.

If you want to help/contribute to extend the tests with automatic
testing/travis happy to talk with you.

2016-08-29 11:26 GMT-04:00 magniff notifications@github.com:

**Comment by magniff** [comment]
Ok, sounds fair.
