### ISSUE TITLE
CRISPResso available on bioconda

### ISSUE THREAD

**Issue by tomkinsc** [lucapinello/CRISPResso#9]
I hope this is OK; I made CRISPResso available for installation via bioconda:
https://bioconda.github.io/recipes/crispresso/README.html

(It's now possible to `conda install crispresso`)

Recipe source on GitHub here:
https://github.com/bioconda/bioconda-recipes/tree/master/recipes/crispresso

I haven't put it through its paces, so it is possible some changes may need to be made to the recipe (especially with respect to dependencies), but in general it is available and should be easy for users to install.

In the future, it would be nice to have tagged releases on GitHub so downstream users can keep track of versions.

Cheers,
Chris

**Comment by lucapinello** [comment]
Chris, this is fantastic! Thanks a lot ! 

RE the tagged releases, it is an excellent idea. I will definitively do that in the future. 

I have just tested the installation with conda and the provided example and  it worked perfectly.

Thanks again!

Luca
